### ISSUE TITLE
Using Babel?

### ISSUE THREAD

**Issue by afshinm** [arashmilani/redux-promises-concluder#1]
Read the code; looks nice. I'm sure you are aware of this but, as a suggestion, why not using Babel transpiler?

I mean:
```
export default function () {
  //pass
}
```

Instead of:

```
module.export = function () {
  /pass
}
```

would make it much easier to read, contribute, digest, etc.

**Comment by arashmilani** [comment]
Thanks @afshinm for bringing this up. Actually I'm thinking why should I introduce a dependency on babel for such a small thing even in development phase of the module? Am I missing something?

**Comment by afshinm** [comment]
Hmm, sure. People think differently. For me, using ES6 works better. Btw, it was just a suggestion, closing.
